#!/bin/bash

#
# git_e17 - enesim plugin
#

#
# PLUGINS:
# - are called via git_e17 <action> plugin <name>
# - need to be in the same path as git_e17!
# - must be named: git_e17-plugin-<name>
# - You can use all functions from git_e17 :)
# - conf will get restored automatically
# - please do not touch other global vars that are
#   used by the script or restore them
#

# this is a hook that will get called fom the main script
plugin_build(){
    local pluign=$1
    section " $1 plugin "

    #packages to be installed
    packages="enesim ender etch egueb"

    #get src
    plugin_get_src


    #build the plugin
    build "" "${conf[build_path]}"
    # build arg1 arg2
    # arg1: relative path to trunk from conf[src_path]
    # arg2: path to source

    #clean up
    packages=""
}

plugin_get_src(){
    echo "source will be checked out to ${conf[build_path]}"

    for pkg in $packages; do
        local pkg_path="${conf[build_path]}/$pkg"
        if [[ -d "$pkg_path" ]]; then
            if [[ ${conf[action]} == update ]]; then
                cd $pkg_path && svn update
            fi
        else
            svn checkout "http://enesim.googlecode.com/svn/trunk/$pkg" "$pkg_path"
        fi
    done
}
